# Generated by Django 5.1.6 on 2025-04-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
