# Generated by Django 5.1.6 on 2025-03-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='allowed_users',
        ),
    ]
