# Generated by Django 5.1.6 on 2025-03-27 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_collection_allowed_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="authorized_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorized_collections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
