# Generated by Django 5.1.6 on 2025-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_collection_authorized_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrowed_books',
            field=models.ManyToManyField(blank=True, related_name='borrowed_by', to='home.book'),
        ),
    ]
