# Generated by Django 5.1.6 on 2025-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_userprofile_borrowed_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_status",
            field=models.CharField(
                choices=[("available", "Available"), ("borrowed", "Borrowed")],
                default="available",
                max_length=9,
            ),
        ),
    ]
