# Generated by Django 5.1.6 on 2025-04-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_borrowrequest_collectionaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_length',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
