# Generated by Django 5.1.6 on 2025-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
